name: Test

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Zmicro
        uses: ./
