name: test

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
      - name: Get version
        id: meta
        run: |
          version=$(echo ${GITHUB_REF} | sed -e "s%refs/tags/%%g")
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Setup Zmicro
        uses: zmicro-design/action-setup-zmicro@${{ steps.meta.outputs.version }}
