name: test

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Zmicro
        uses: zmicro-design/action-setup-zmicro@v1.0.2
